
CREATE TABLE IF NOT EXISTS COMPONENT (
  ITEM_REFERENCE_ID				NUMBER(11,0) 	NOT NULL,
  PUBLICATION_ID			    NUMBER(11,0) 	NOT NULL,
  SCHEMA_ID				        NUMBER(11,0) 	NOT NULL,
  IS_MULTIMEDIA                 NUMBER(11,0)    DEFAULT 0   NOT NULL
);


CREATE TABLE IF NOT EXISTS PAGE (
  ITEM_REFERENCE_ID				NUMBER(11,0) 	NOT NULL,
  PUBLICATION_ID			NUMBER(11,0) 	NOT NULL,
  FILENAME 				VARCHAR2(255) 	NULL,
  URL					VARCHAR2(255)   NOT NULL,
  TEMPLATE_ID				INTEGER		NOT NULL
);


CREATE TABLE IF NOT EXISTS BINARY (
  ITEM_REFERENCE_ID				NUMBER(11,0) 	NOT NULL,
  PUBLICATION_ID			NUMBER(11,0) 	NOT NULL,
  TYPE 					VARCHAR2(255) 	NOT NULL
);


CREATE TABLE IF NOT EXISTS TEMPLATE (
  ITEM_REFERENCE_ID				NUMBER(11,0) 	NOT NULL,
  PUBLICATION_ID			NUMBER(11,0) 	NOT NULL,
  TEMPLATE_PRIORITY			NUMBER(11,0) 	NOT NULL,
  TEMPLATE_OUTPUT_FORMAT		VARCHAR2(64) 	NOT NULL
);


CREATE TABLE IF NOT EXISTS KEYWORD (
  ITEM_REFERENCE_ID				NUMBER(11,0)	NOT NULL,
  PUBLICATION_ID			NUMBER(11,0)	NOT NULL,
  KEYWORD_NAME				VARCHAR2(255)	NOT NULL
);


CREATE TABLE IF NOT EXISTS TDS_DB_INFO(
 DB_VERSION        VARCHAR2(510)	     NULL
, DESCRIPTION        VARCHAR2(510)	     NULL
, INSTALLATION_TYPE     VARCHAR2(510)	     NULL
, LAST_MODIFIED       VARCHAR2(510)	     NULL
, MODIFIED_BY        VARCHAR2(510)	     NULL
);


CREATE TABLE IF NOT EXISTS REFERENCE_ENTRIES(
  PUBLICATION_ID				NUMBER(11,0)  	NOT NULL
, REFERENCED_URI 				VARCHAR2(440) 	NOT NULL
, REFERENCING_URI  			VARCHAR2(440)	NOT NULL
);


CREATE TABLE IF NOT EXISTS LINK_INFO(
  PUBLICATION_ID 				NUMBER(11,0) 	NOT NULL
, PAGE_ID 					NUMBER(11,0) 	NOT NULL
, COMPONENT_ID 				NUMBER(11,0) 	NOT NULL
, COMPONENT_TEMPLATE_ID 		NUMBER(11,0) 	NOT NULL
, COMPONENT_TEMPLATE_PRIORITY 	NUMBER(11,0) 	NOT NULL
, COMPONENT_POSITION 			NUMBER(11,0) 	NOT NULL
, URL VARCHAR2(510) NULL
);


CREATE TABLE IF NOT EXISTS ITEMS(
  ITEM_REFERENCE_ID 			NUMBER(11,0) 	NOT NULL
, PUBLICATION_ID 				NUMBER(11,0) 	NOT NULL
, MAJOR_VERSION 				NUMBER(11,0) 	NULL
, MINOR_VERSION 				NUMBER(11,0) 	NULL
, OWNING_PUBLICATION_ID 		NUMBER(11,0) 	NULL
, ITEM_TYPE 				NUMBER(11,0) 	NOT NULL
, TITLE 					VARCHAR2(510) 	NOT NULL
, CREATION_DATE 				TIMESTAMP 			NULL
, INITIAL_PUBLICATION_DATE 		TIMESTAMP 			NULL
, LAST_PUBLISHED_DATE 			TIMESTAMP 			NULL
, TRUSTEE 					VARCHAR2(510) 	NULL
, MODIFICATION_DATE 			TIMESTAMP 			NULL
, ITEM_SELECTOR				VARCHAR2(50)		NULL
);


CREATE TABLE IF NOT EXISTS BINARYVARIANTS(
  PUBLICATION_ID 				NUMBER(11,0) 	NOT NULL
, BINARY_ID 				NUMBER(11,0) 	NOT NULL
, VARIANT_ID				VARCHAR2(128)	DEFAULT '[#def#]' NOT NULL
, PATH 					VARCHAR2(510) 	NOT NULL
, DESCRIPTION 				VARCHAR2(510) 	DEFAULT ' '	NULL
, IS_COMPONENT 				NUMBER(11,0) 	DEFAULT 0	NOT NULL
, URL					VARCHAR2(510) NULL
, TYPE 					VARCHAR2(255) 	NOT NULL
);


CREATE TABLE IF NOT EXISTS COMPONENT_PRESENTATIONS(
  PUBLICATION_ID 				NUMBER(11,0) 	NOT NULL
, COMPONENT_ID 				NUMBER(11,0) 	NOT NULL
, TEMPLATE_ID 				NUMBER(11,0) 	NOT NULL
, CONTENT 					BLOB 			NOT NULL
);


CREATE TABLE IF NOT EXISTS COMPONENT_PRES_META_DATA(
  PUBLICATION_ID 			NUMBER(11,0) 	NOT NULL
, COMPONENT_REF_ID 			NUMBER(11,0) 	NOT NULL
, COMPONENT_TEMPLATE_ID 		NUMBER(11,0) 	NOT NULL
, COMPONENT_OUTPUT_FORMAT 				VARCHAR2(25) 	NOT NULL
, ENCODING						VARCHAR2(50) NULL
);


CREATE TABLE IF NOT EXISTS CUSTOM_META (
CUSTOM_META_VALUE_ID NUMBER(11,0) NOT NULL
, PUBLICATION_ID NUMBER(11,0) NOT NULL
, ITEM_ID NUMBER(11,0) NOT NULL
, ITEM_TYPE NUMBER(11,0) NOT NULL
, KEY_NAME VARCHAR2(255) NOT NULL
, KEY_TYPE NUMBER(11,0) NOT NULL
, KEY_DATE_VALUE TIMESTAMP NULL
, KEY_STRING_VALUE VARCHAR2(4000) NULL
, KEY_FLOAT_VALUE NUMBER NULL 
);


CREATE TABLE IF NOT EXISTS SCHEMAS (
  PUBLICATION_ID		NUMBER(11,0)	NOT NULL,
  SCHEMA_ID				NUMBER(11,0)	NOT NULL,
  TITLE					VARCHAR2(510),
  CONTENT 				CLOB			NOT NULL 
);


CREATE TABLE IF NOT EXISTS BINARY_CONTENT (
  PUBLICATION_ID		NUMBER(11,0)	NOT NULL,
  BINARY_ID				NUMBER(11,0)	NOT NULL,
  VARIANT_ID				VARCHAR2(128)	DEFAULT '[#def#]' NOT NULL,
  CONTENT 				BLOB			NOT NULL 
);


CREATE TABLE IF NOT EXISTS XSLT_CONTENT (
  PUBLICATION_ID		NUMBER(11,0)	NOT NULL,
  XSLT_ID				NUMBER(11,0)	NOT NULL,
  LAST_MODIFIED			TIMESTAMP			NOT NULL,
  CONTENT 				CLOB			NULL 
);


CREATE TABLE IF NOT EXISTS PAGE_CONTENT (
  PUBLICATION_ID		NUMBER(11,0)	NOT NULL,
  PAGE_ID				NUMBER(11,0)	NOT NULL,
  CONTENT 				CLOB			NOT NULL, 
  CHARSET				VARCHAR2(40)	NULL
);


CREATE TABLE IF NOT EXISTS PUBLICATIONS (
  PUBLICATION_ID		INTEGER			NOT NULL,
  PUBLICATION_TITLE		VARCHAR2(255),
  PUBLICATION_KEY		VARCHAR2(255),
  PUBLICATION_PATH 		VARCHAR2(255),
  PUBLICATION_URL 		VARCHAR2(255),
  MULTIMEDIA_PATH 		VARCHAR2(255),
  MULTIMEDIA_URL 		VARCHAR2(255)
);


CREATE TABLE IF NOT EXISTS DYNAMIC_LINKS
   (
    SRC_PUB_ID     NUMBER(11,0) NOT NULL,
    SRC_ITEM_ID     NUMBER(11,0) NOT NULL,
    SRC_ITEM_TYPE NUMBER(11,0) NOT NULL,
    DST_PUB_ID     NUMBER(11,0) NOT NULL,
    DST_ITEM_ID     NUMBER(11,0) NOT NULL,
    DST_ITEM_TYPE NUMBER(11,0) NOT NULL
);


CREATE TABLE IF NOT EXISTS TAXFACETS (
  NODE_ID			NUMBER(11,0)    NOT NULL,
  FACET_ID			NUMBER(11,0)	NOT NULL,
  PUBLICATION_ID		NUMBER(11,0)	NOT NULL,
  TAXONOMY_ID			NUMBER(11,0)	NOT NULL,
  FACET_NAME			VARCHAR2(255)	NOT NULL,
  FACET_DESCRIPTION		VARCHAR2(255)	NULL,
  FACET_KEY			VARCHAR2(255)	NULL,
  FACET_PARENT			VARCHAR2(50)	NULL,
  FACET_ISABSTRACT		NUMBER(11,0)	NOT NULL,
  FACET_ISNAVIGABLE		NUMBER(11,0)	NOT NULL,
  FACET_HASCHILDREN		NUMBER(11,0)	NOT NULL,
  FACET_DEPTH			NUMBER(11,0)	NOT NULL,
  FACET_LEFT			NUMBER(11,0)	NOT NULL,
  FACET_RIGHT			NUMBER(11,0)	NOT NULL,
  FACET_ITEMTYPE		NUMBER(11,0)	NOT NULL,
  ITEM_SELECTOR			VARCHAR2(50)	DEFAULT 'Keyword' NOT NULL,
  FACET_ISUSEDFORIDENTIFICATION		NUMBER(11,0) DEFAULT 0	NOT NULL,
  TOTAL_RELATEDITEMS	NUMBER(11,0) DEFAULT 0 NOT NULL
);


CREATE TABLE IF NOT EXISTS ITEM_CATEGORIES_AND_KEYWORDS(
  RELATION_ID				NUMBER(11,0)	NOT NULL
, ITEM_REFERENCE_ID 			NUMBER(11,0)	NOT NULL
, PUBLICATION_ID 				NUMBER(11,0) 	NOT NULL
, TAXONOMY_ID 					NUMBER(11,0)    DEFAULT -1 NOT NULL
, KEYWORD_ID 					NUMBER(11,0)    DEFAULT -1 NOT NULL
, CATEGORY 					VARCHAR2(510) 	NOT NULL
, KEYWORD 					VARCHAR2(510) 	NOT NULL
, TAXFACET_TYPE 			NUMBER(11,0)    NOT NULL
);


CREATE TABLE IF NOT EXISTS KEYWORD_RELATIONS(
  NODE					NUMBER(11,0) 	NOT NULL
, KEYWORD_TO					NUMBER(11,0)    NOT NULL
);


CREATE TABLE IF NOT EXISTS PREVIEW_SESSIONS(
  PREVIEW_SESSION_ID				VARCHAR2(50) NOT NULL
, EXPIRATION_DATE				TIMESTAMP NOT NULL
);


CREATE TABLE IF NOT EXISTS PREVIEW_SESSION_ITEMS(
  PREVIEW_SESSION_ID				VARCHAR2(50) NOT NULL
, PREVIEW_SESSION_OBJECT_KEY				VARCHAR2(290) NOT NULL
, INSTANCE_NAME				VARCHAR2(100) NOT NULL
, FILEPATH				CLOB
, CHANGED_ON_DISK   NUMBER(1,0)    DEFAULT 0   NOT NULL
, STATE				NUMBER(2,0) NOT NULL
);


CREATE TABLE IF NOT EXISTS PUBLICATION_MAPPINGS(
  VIRTUAL_PUBLICATION_ID				INTEGER NOT NULL
, REAL_PUBLICATION_ID				INTEGER NOT NULL
, MAPPING_KEY				VARCHAR2(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS UNDO_TRANSACTIONS(
TRANSACTION_ID				VARCHAR2(50) NOT NULL
, CREATION_DATE				TIMESTAMP NOT NULL
);


CREATE TABLE IF NOT EXISTS UNDO_LOG(
TRANSACTION_ID				VARCHAR2(50) NOT NULL
, OBJECT_KEY				VARCHAR2(290) NOT NULL
, UNDO_STATE				NUMBER(2,0) NOT NULL
);


CREATE TABLE IF NOT EXISTS EXTENSION_DATA (
    PUBLICATION_ID  INTEGER NOT NULL,
    OBJECT_KEY      VARCHAR2(290) NOT NULL,
    CONTENT         CLOB NOT NULL
);


